### ISSUE TITLE
Change the color of either html/jsx tags or plain text in children ?

### ISSUE THREAD

**Issue by florentlalise** [TrueBabyChaise/Serena-Dark-Theme#2]
![image](https://github.com/TrueBabyChaise/Serena-Dark-Theme/assets/59749345/c16de3b1-0f73-47b5-8871-81cfb2410b39)

**Comment by TrueBabyChaise** [comment]
I changed the color, to a blue one
![image](https://github.com/TrueBabyChaise/Serena-Dark-Theme/assets/72005357/0577139c-7ec0-4228-857d-9fcaa7199326)
