### ISSUE TITLE
Change the color of either string or html attribute?

### ISSUE THREAD

**Issue by florentlalise** [TrueBabyChaise/Serena-Dark-Theme#3]
They have the same color, so it can be hard to read if an html tag has a lot of attributes.

![image](https://github.com/TrueBabyChaise/Serena-Dark-Theme/assets/59749345/b687f1ee-7889-4fd6-bfd2-087c90f1371d)

**Comment by TrueBabyChaise** [comment]
I put the tag in color, a dark pink
